version: '3.8'

services:
  web:
    build: .
    container_name: curriculum_app_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:312004@host.docker.internal:5432/curriculum_db